### ISSUE TITLE
Convert street addresses into coordinates with geocoding

### ISSUE THREAD

**Issue by NickLee808** [aukai84/akahele#54]
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by NickLee808** [comment]
Feature complete once I get the test data to show up

**Comment by NickLee808** [comment]
Spent waaaaay too much time on this already. Can't seem to find a reliable service to convert coordinates accurately

**Comment by ghost** [comment]
MapBox
https://www.mapbox.com/geocoding/

has one caveat:

> Use our free geocoder with any Mapbox plan as long as the results are displayed on a Mapbox map.

https://geocod.io/pricing/ same req limit and pricing as google

**Comment by theRemix** [comment]
if you cache your google requests, you should not be hitting your limits as much.
better, all requests hit your own api endpoint (not straight to the googs) then you can returned cached results.

if you don't cache, then mapbox will give you the same issues.

**Comment by NickLee808** [comment]
setInterval() saves the day! Still fiddling with the proper time interval between geocodes in order to get all data points, but it should be all over soon...

**Comment by NickLee808** [comment]
Even at two seconds between geocodes, I am still getting OVER_QUERY_LIMIT for a big HALF of the results. I think I'm going to keep the intervals at two seconds apart, but implement some kind of redo for anything that gets OVER_QUERY_LIMIT as a status until it returns OK.

**Comment by NickLee808** [comment]
setInterval() lowered to 300, able to code all addresses by redoing any that stuck at OVER_QUERY_LIMIT until it returns OK
